tests:
  services:
    - postgres:9.5
  script:
    - pip install -e .
    - mv .env.test .env
    - ./setupdb.sh
    - nosetests tests
  tags: ["angr"]

# lint:
#   script: "lint.py"
#   tags: ["cgc-linter"]

docs:
  script: "generate_docs"
  tags: ["cgc-linter"]
