stages:
  - test
  - build
  - deploy

tests:
  services:
    - postgres:9.5
  script:
    - pip install --process-dependency-links -U -e .
    - ./setupdb.sh .env.test
    - nosetests tests
  tags: ["angr"]

# lint:
#   script: "lint.py"
#   tags: ["cgc-linter"]

docs:
  stage: build
  script: "generate_docs"
  tags: ["cgc-linter"]

build_worker:
  stage: build
  only: ["master"]
  script:
  - cgc-build worker
  tags: ["docker-builder"]

build_meister:
  stage: build
  only: ["master"]
  script:
  - cgc-build meister
  tags: ["docker-builder"]

build_scriba:
  stage: build
  only: ["master"]
  script:
  - cgc-build scriba
  tags: ["docker-builder"]

build_ambassador:
  stage: build
  only: ["master"]
  script:
  - cgc-build ambassador
  tags: ["docker-builder"]

update_vm_image:
  stage: build
  only: ["master"]
  script:
  - update-vm-image
  tags: ["docker-builder"]

production:
  stage: deploy
  only: ["master"]
  script:
  - docker tag worker 172.16.7.72/worker:stable
  - docker push 172.16.7.72/worker:stable
  - docker tag meister 172.16.7.72/meister:stable
  - docker push 172.16.7.72/meister:stable
  - docker tag scriba 172.16.7.72/scriba:stable
  - docker push 172.16.7.72/scriba:stable
  - docker tag ambassador 172.16.7.72/ambassador:stable
  - docker push 172.16.7.72/ambassador:stable
  environment: production
  tags: ["docker-builder"]
